### ISSUE TITLE
Throttle down

### ISSUE THREAD

**Issue by eriweb** [philbennett94/cosmosdb-scaling-with-azure-functions#1]
How about automatic throttling down when the burst traffic has ended?

**Comment by phil-bennett** [comment]
Hi terbolous. this code is stale as of the last commit (many months ago... longer?) and is not actively updated. 

_For your ask_: Gather telemetry using diagnostic logging features in Cosmos DB (https://docs.microsoft.com/en-us/azure/cosmos-db/logging) and/or azure monitor. Call density info will give you more granular and informed control on scaling your collections. The code shown here shouldn't be used in production - it is simply a starting point. 

I will post more code after Microsoft's OneWeek hackathon that will provide detailed examples of autonomous scaling patterns and mount/dismount resource management architecture, however Cosmos DB will not be a part of the product collection present in example set.
